In [1]:
#Perform Matrix Manipulation on Stock Price Data
import numpy as np

# Stock 1 price data (5 days × 3 features: Open, High, Low)
stock1 = np.array([
    [100,105,98],
    [102,108,101],
    [104,110,103],
    [103,107,100],
    [105,111,104]
])

# Stock 2 price data (5 days × 3 features: Open, High, Low)
stock2 = np.array([
    [98,103,95],
    [101,106,99],
    [103,109,101],
    [102,105,98],
    [104,110,102]
])

# Element-wise sum (combined price values)
sum_matrix = stock1 + stock2

# Element-wise difference (daily spread)
diff_matrix = stock1 - stock2

print("Stock 1 Data:")
print(stock1)

print("\nStock 2 Data:")
print(stock2)

print("\nElement-wise Sum of the Two Stocks:")
print(sum_matrix)

print("\nElement-wise Difference (Daily Spread Between Stocks):")
print(diff_matrix)

Stock 1 Data:
[[100 105  98]
 [102 108 101]
 [104 110 103]
 [103 107 100]
 [105 111 104]]

Stock 2 Data:
[[ 98 103  95]
 [101 106  99]
 [103 109 101]
 [102 105  98]
 [104 110 102]]

Element-wise Sum of the Two Stocks:
[[198 208 193]
 [203 214 200]
 [207 219 204]
 [205 212 198]
 [209 221 206]]

Element-wise Difference (Daily Spread Between Stocks):
[[2 2 3]
 [1 2 2]
 [1 1 2]
 [1 2 2]
 [1 1 2]]
